version: "3.9"
services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3
    ports:
      - "54321:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data:cached
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  app-db-data: